// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwz8wJhSFS0ny9u1jmNFmtbfI_Fcf6Bss',
    appId: '1:445233198990:web:4bd7f49f487df5074296df',
    messagingSenderId: '445233198990',
    projectId: 'cogito-d1f6b',
    authDomain: 'cogito-d1f6b.firebaseapp.com',
    storageBucket: 'cogito-d1f6b.appspot.com',
    measurementId: 'G-MRVSM0MJ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYPfAYu9jXrA1oXLcCx4ZXKGKlHhzPAUg',
    appId: '1:445233198990:android:4a4cf2cca544f2e54296df',
    messagingSenderId: '445233198990',
    projectId: 'cogito-d1f6b',
    storageBucket: 'cogito-d1f6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOggoKUSvS20MttQq-Pjs5TqyOZd_6An8',
    appId: '1:445233198990:ios:7ce370532aa0f2b64296df',
    messagingSenderId: '445233198990',
    projectId: 'cogito-d1f6b',
    storageBucket: 'cogito-d1f6b.appspot.com',
    iosBundleId: 'com.example.cogito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOggoKUSvS20MttQq-Pjs5TqyOZd_6An8',
    appId: '1:445233198990:ios:7ce370532aa0f2b64296df',
    messagingSenderId: '445233198990',
    projectId: 'cogito-d1f6b',
    storageBucket: 'cogito-d1f6b.appspot.com',
    iosBundleId: 'com.example.cogito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwz8wJhSFS0ny9u1jmNFmtbfI_Fcf6Bss',
    appId: '1:445233198990:web:81d74d9212c5d51f4296df',
    messagingSenderId: '445233198990',
    projectId: 'cogito-d1f6b',
    authDomain: 'cogito-d1f6b.firebaseapp.com',
    storageBucket: 'cogito-d1f6b.appspot.com',
    measurementId: 'G-1ZMSCFXH45',
  );
}
